#!/bin/bash

set -e

OPATH=$PATH

GITHUB_USERNAME="returntrip"
REPO="bitwarden/sdk"
TEMP_DIR=$(mktemp -d)

export PATH=$TEMP_DIR:$PATH

# Get the latest release URL
RELEASE_ARCHIVE_URL=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | grep -Eo 'https://[^"]*' | grep 'bws-x86_64-unknown-linux-gnu-')

# Download the release ZIP
curl -sLo "$TEMP_DIR/bws-x86_64-unknown-linux-gnu-latest.zip" "$RELEASE_ARCHIVE_URL"
# Extract the ZIP in the output directory
unzip -q "$TEMP_DIR/bws-x86_64-unknown-linux-gnu-latest.zip" -d "$TEMP_DIR"

sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply "$GITHUB_USERNAME"

export PATH=$OPATH
