{{- $work := false -}}{{/* true if this machine is used for work */}}
{{- $personal := false -}}{{/* true if this machine is for personal usage */}}

[git]
    autoCommit = true

[data]
    work_mail = "stefano.figura@tietoevry.com"
    personal_mail = "stefano@figura.im"
